resources:
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml

patches:
  - target:
      kind: Deployment
      name: rabbitmq-cluster-operator
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: cluster-b-worker2
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "dedicated"
            operator: "Equal"
            value: "rabbitmq"
            effect: "NoSchedule"