apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-secret
  namespace: ms-demo-{{ target.name }}
spec:
  path: "secret/ghcr/credentials"
  type: kubernetes.io/dockerconfigjson
  keys:
    - username
    - password
  templates:
    ".dockerconfigjson": |
      {% raw %}{"auths":{"ghcr.io":{"username":"{% .Secrets.username %}","password":"{% .Secrets.password %}","auth":"{% list .Secrets.username ":" .Secrets.password | join "" | b64enc %}"}}}{% endraw %}