apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: rabbitmq-credentials
  namespace: ms-demo-{{ target.name }}
spec:
  path: secret/rabbitmq/config
  type: Opaque
  keys:
    - username
    - password
  # - erlang-cookie
  templates:
    username: >-
      {% raw %}{% .Secrets.username %}{% endraw %}
    password: >-
      {% raw %}{% .Secrets.password %}{% endraw %}
    # erlang-cookie: >-
    #   {% raw %}{% index .Secrets "erlang-cookie" %}{% endraw %}