apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: clusterb-secret
  namespace: ms-demo-{{ target.name }}
spec:
  path: secret/clusterb
  type: Opaque
  keys:
    - password
  templates:
    password: "{% raw %}{% .Secrets.password %}{% endraw %}"