# PHASE 3: Allow the Job to exec into Vault
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-setup-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-setup-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: vault-setup-role
  apiGroup: rbac.authorization.k8s.io