apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30000