# PHASE 3: ConfigMap for Vault config script (vault-dev only)
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-setup-script
data:
  cluster_b_ca_cert_b64: "{{ cluster_b_ca_cert | b64encode }}"
  configure-vault.sh: |
    #!/bin/sh
    set -e

    VAULT_ADDR="http://vault:8200"
    export VAULT_ADDR

    echo "Waiting for Vault to be ready..."
    until vault status; do sleep 2; done

    vault auth enable kubernetes || true

    # Decode the base64 CA cert (avoids YAML/shell quoting issues)
    echo "{{ cluster_b_ca_cert_b64 }}" | base64 -d > /tmp/ca.crt
    

    vault write auth/kubernetes/config \
      kubernetes_host="{{ cluster_b_api }}" \
      kubernetes_ca_cert=@/tmp/ca.crt \
      token_reviewer_jwt="{{ token_reviewer_jwt }}" || true

    echo '
    path "secret/data/*" {
      capabilities = ["read","list"]
    }' > /tmp/vault-secrets-operator-policy.hcl

    vault policy write vault-secrets-operator /tmp/vault-secrets-operator-policy.hcl || true

    vault write auth/kubernetes/role/vault-secrets-operator \
      bound_service_account_names=vault-secrets-operator \
      bound_service_account_namespaces=ms-demo-app-dev \
      policies=vault-secrets-operator \
      ttl=1h || true

    vault kv put secret/clusterb password="s3cr3t-p@ssw0rd" || true
