sysctlImage:
  enabled: true
  command: ["/bin/sh", "-c", "sysctl -w fs.file-max=100000 && ulimit -n 100000"]
  securityContext:
    privileged: true

nodeSelector:
  kubernetes.io/hostname: cluster-b-worker3