apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: ms-demo-{{ target.name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      nodePort: 30001  # Must be 30000-32767