vault_root_token: "root"
vault_cluster_a_ip: "172.20.0.3"
cluster_b_api: "https://172.20.0.6:6443"
cluster_b_ca_cert: |-
  -----BEGIN CERTIFICATE-----
  MIIDBTCCAe2gAwIBAgIIIo4SyXsSBu4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
  AxMKa3ViZXJuZXRlczAeFw0yNTA3MTgwNTI3MjBaFw0zNTA3MTYwNTMyMjBaMBUx
  EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQCt04nxNPI4FoCA/94U0Z9HPO3fLEHUpSpdmNljG67THddGbbvgFkRcvO1d
  tjF3rNYs5ymgZup9m1Xu0ZLd7TBDvdoL0dLOJXtNeIWQJLguKjKe8BHMNYpA6o4o
  kR7ncORi7aIymmg7nkgHwExeFPUr+a59V0Yneyb1Rx6tNi9aQA9m18jwCfLr+pQF
  4YnruefUsDf0nu+iTsbp3Bdkc04M5bpa24CMQZLy9WHgUuRtsvsue5Q3pJC27jbZ
  6xiJcnnTvYGBBTA2l6rxKMzDru5ElAKidQZZRmr0czKC15qqfuUohx1eqH8f2GSy
  s1etlw0UgkV5wrPBnEXddteAP7ivAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
  BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSbTuy8XB43YRYWidg9eZvmUYGt7zAV
  BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAGq3b5CyvR
  jeUns+rAHclzUhXaZrmRUqwGM01rORVWFwFFRLwJhipyvyHD/DQAqH3kvopB5z7O
  f1dHAD8mk42acgeuHDb6SY4Uzt6PCGX2ISKdcnbW2rpyv1dJMAVdp4gIQxeBPcFU
  s9Wu/QC+BF5w8bFttiU9Z5z4fpLRbIpvDfhhzlH/bv7l/Un5DWZICOxcGrGuvahk
  Qw1hyshs8PEE8JFmkyEcTsRKkp8ygzAcdu03h6ob8fSzNPXWGpPIFa11+vsuMKtV
  eMkSa52tkdo7/t84/qyAjJYqIBub1/EcL71/hp4HR0xViML+ebaf7M1hojF/Ekd4
  lj2ALk/idQDB
  -----END CERTIFICATE-----
token_reviewer_jwt: "eyJhbGciOiJSUzI1NiIsImtpZCI6InFZbTlFWlRnd2lMSDhpcHV6X2U3Rks3RkpPY0x2enpSTk1Ja2l2dXVsQWMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzg0MzU0MzI2LCJpYXQiOjE3NTI4MTgzMjYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMjYxZDkzMTctZTk5Zi00MjFkLTk1ZmYtMzE1ODIwNWMwYjBhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJtcy1kZW1vLWFwcC1kZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoidmF1bHQtYXV0aCIsInVpZCI6IjE4OGNjZDc0LWMzNDctNGQ0Ny05Mzg5LWMxZmI4ZTdmZGNmMSJ9fSwibmJmIjoxNzUyODE4MzI2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bXMtZGVtby1hcHAtZGV2OnZhdWx0LWF1dGgifQ.boTh1Z4YAREWwhfxduZxSKNnRIrGsL3oCtx8tHE5SwhsDQPu4adUir1GUPgRrMjrDbh1K6558XU5DvY7v4y9IBGsD3YfZX8E3FocqbOHTLIVTcUYAdmc0KWibDYDaZ-iuNcRXCB64ZwYEmSLWORuKbbxA-D0RZclJp7r415iRtXFWNKcWW6Esezl4tmrsBpj2dqbrrVjVFlLhoDlr2u6aF1Zp67O09krKk_2ugEqW3FiEmtXwWUnR5M-yhiLfUei4yjiIiXxAewCc9qnS4GrgMDOwObdjPVp3rwQhkq3qMTDas90f3Ps8X0LVIca7C63iO6o09Qoo_VgMqI81tibyQ"
