apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "rabbitmq-cluster"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/secret-volume-path: "/etc/rabbitmq/conf.d"
    vault.hashicorp.com/agent-inject-secret-11-default_user.conf: "secret/data/rabbitmq"
    vault.hashicorp.com/agent-inject-template-11-default_user.conf: |
      {% raw %}{{- with secret "secret/data/rabbitmq" -}}
      default_user = {{ .Data.data.username }}
      default_pass = {{ .Data.data.password }}
      {{- end -}}{% endraw %}
    vault.hashicorp.com/template-static-secret-render-interval: "15s"
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
  secretBackend:
    vault:
      role: rabbitmq-cluster
      defaultUserPath: secret/data/rabbitmq
      defaultUserUpdaterImage: rabbitmqoperator/default-user-credential-updater:1.0.1
  override:
    statefulSet:
      spec:
        template:
          spec:
            initContainers:
            - name: setup-container
              command:
              - sh
              - -c
              - |
                cp /tmp/erlang-cookie-secret/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie && chmod 600 /var/lib/rabbitmq/.erlang.cookie ; 
                cp /tmp/rabbitmq-plugins/enabled_plugins /operator/enabled_plugins ; 
                echo '[default]' > /var/lib/rabbitmq/.rabbitmqadmin.conf ; 
                [ -f /etc/rabbitmq/conf.d/11-default_user.conf ] && sed -e 's/default_user/username/' -e 's/default_pass/password/' /etc/rabbitmq/conf.d/11-default_user.conf >> /var/lib/rabbitmq/.rabbitmqadmin.conf || true ; 
                chmod 600 /var/lib/rabbitmq/.rabbitmqadmin.conf ; 
                sleep 30
            containers:
            - name: rabbitmq
              env:
              - name: RABBITMQ_ERLANG_COOKIE
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-credentials
                    key: erlang-cookie