# rabbitmq-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: ms-demo-{{ target.name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: vault-default-user
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      # Custom port (30000-32767)
      nodePort: 30672  
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672